version: "2"

run:
  timeout: 5m

output:
  formats:
    tab:
      path: stdout

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - durationcheck
    - errorlint
    - forbidigo
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives

formatters:
  enable:
    - gofmt
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
