name: 'GitHub and Asana Pull Request Task integration.'
description: 'When a reviewer is assigned on GitHub, creates a review subtask on an Asana task specified in a pull request description.'
author: 'Keita Kitamura <keitap@gmail.com>'
inputs:
  config_path:
    required: false
    description: 'Path for GitHub and Asana account mapping config file.'
    default: '.github/github-asana-request-review.yml'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/keitap/github-asana-request-review-action:1.1.5'
branding:
  icon: 'refresh-cw'
  color: 'gray-dark'
